### ISSUE TITLE
签名api异常： wtlogin.login result(4ms): {"code":-1,"msg":"connect ECONNREFUSED 127.0.0.1:8080"}

### ISSUE THREAD

**Issue by 112121212167987534524** [CikeyQi/unidbg-fetch-qsign-shell#1]
[qsign]签名api异常： wtlogin.exchange_emp result(3ms): {"code":-1,"msg":"connect ECONNREFUSED 127.0.0.1:8080"}

**Comment by AltinaSchwarzer** [comment]
一样[qsign]签名api(energy)异常： 810_9 result(5ms): {"code":-1,"msg":"connect ECONNREFUSED 127.0.0.1:8080"}
[MiaoYz][13:40:47.336][ERRO] [qsign]签名api异常： wtlogin.login result(4ms): {"code":-1,"msg":"connect ECONNREFUSED 127.0.0.1:8080"}
[MiaoYz][13:40:47.369][MARK] 120.232.130.13:8080 connected

**Comment by CikeyQi** [comment]
已知无法在ARM设备上正常运行，若非ARM设备请进一步反馈qsign的日志内容

**Comment by wudifeixue** [comment]
在ARM上能用的我用了这个：https://github.com/touchscale/Qsign
目前成功在8.9.93跑起来了
使用协议：Android_8.9.93.13475
之所以为何用这个，是因为今天，就在几个小时前，huggingface把这个白嫖的项目给炸了，
https://github.com/CikeyQi/QQsign_docs
包括原作者和我自己的账号貌似都被一口气给删了
