### ISSUE TITLE
相关问题解决方案

### ISSUE THREAD

**Issue by CikeyQi** [CikeyQi/unidbg-fetch-qsign-shell#10]
- 如何确保服务正在运行？
  - 使用 `curl` 命令，格式：`curl http://127.0.0.1:8080`，请将格式中8080端口号替换为设置好的端口号

-  如何查看运行日志？
   - 如果选择的是使用 **systemd管理** ，请运行qsign_operations.sh脚本，选择8即可输出运行日志
   - 如果选择的是使用 **Docker管理**，请运行`docker logs 容器名称`，即可输出运行日志

- 如何更改使用 **systemd管理** 时运行的端口？
  - 请进入 **/unidbg-fetch-qsign-1.1.9/txlib/<使用的版本号>/config.json**，修改server.port即可，默认运行在8080端口上

**Comment by crx9** [comment]
systemd哪里修改端口
