### ISSUE TITLE
[BUG] 使用8.9.90时一段时间后签名服务会不可用？

### ISSUE THREAD

**Issue by JUST-HK416D** [CikeyQi/unidbg-fetch-qsign-shell#13]
用的最新发行版go-cq和8.9.90协议，签名服务器启动的一段时间内没啥问题，过了几个小时后在go-cq无法发出消息，查看控制台提示
```log
[2024-02-01 14:38:08] [WARNING]: 获取sso sign时出现错误: Post "http://127.0.0.1:8080/sign": context deadline exceeded (Client.Timeout exceeded while awaiting headers). server: http://127.0.0.1:8080
```
随后杀死qsign后重新启动又正常可用，后续补充qsign日志

**Comment by CikeyQi** [comment]
出现问题时，qsign程序仍然正常运行还是已经终止运行？

**Comment by YugaoX** [comment]
> 出现问题时，qsign程序仍然正常运行还是已经终止运行？

看起来和楼主有同样的问题 qsign应该是已经停止运行了 重启后即可恢复

**Comment by CikeyQi** [comment]
Docker方法部署可以做到自动重启

**Comment by JUST-HK416D** [comment]
> 出现问题时，qsign程序仍然正常运行还是已经终止运行？

回晚了sry，我的情况是qsign任然在运行中，我现在变成跑一个shell脚本去post http://127.0.0.1:8080/sign如果超时就直接杀掉qsign然后重启，但是好像qsign不可用的时候go-cq还是会尝试发消息导致容易冻结，我得去看看go-cq的配置了:(
