### ISSUE TITLE
如何配置开启自动注册实例

### ISSUE THREAD

**Issue by INKCR0W** [CikeyQi/unidbg-fetch-qsign-shell#18]
使用go-cqhttp时抛出了一个警告，内容如下
`[WARNING]: 自动注册实例已关闭，请配置 sign-server 端自动注册实例以保持正常签名`
因为原项目已删库，文档也无处可查，请问如何修改配置以开启这个功能

**Comment by CikeyQi** [comment]
`unidbg-fetch-qsign/txlib/<你选择的协议版本>/config.json` 中的 `auto_register` 的值为 `true` ，即为开启自动注册实例。
