### ISSUE TITLE
如何在go-cqhttp中使用

### ISSUE THREAD

**Issue by yushengjiaohuang** [CikeyQi/unidbg-fetch-qsign-shell#2]
如题

**Comment by CikeyQi** [comment]
在[Actions](https://github.com/Mrs4s/go-cqhttp/actions)下载CI构建的dev分支的gocq，启动后在config.yml可看见如图配置，如图所示配置即可
![image](https://github.com/CikeyQi/unidbg-fetch-qsign-shell/assets/61369914/24d1ee31-e52b-4fed-89d4-4291ff03674e)

**Comment by yushengjiaohuang** [comment]
对了 yunzai那个协议是在qq.yaml里面，不是bot.yaml
