### ISSUE TITLE
解压时报错，日志如下

### ISSUE THREAD

**Issue by wzq10314** [CikeyQi/unidbg-fetch-qsign-shell#3]
正在下载并检查所需软件包，请稍等...
已安装 pv 工具，跳过安装
已安装 unzip 工具，跳过安装
已安装 Java 环境，跳过安装
1) 国内线路
2) 国外线路
请选择线路：2
正在下载 unidbg-fetch-qsign，请稍等...
9.00 B [================================================================================================================================================================>] 100%            
下载 unidbg-fetch-qsign 完成，开始解压...
[unidbg-fetch-qsign.3.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of unidbg-fetch-qsign.3.zip or
        unidbg-fetch-qsign.3.zip.zip, and cannot find unidbg-fetch-qsign.3.zip.ZIP, period.
解压失败，请确保 zip 工具已安装并可用

**Comment by wzq10314** [comment]
debian无法使用吗

**Comment by wzq10314** [comment]
手动解压报错内容
Archive:  unidbg-fetch-qsign.3.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of unidbg-fetch-qsign.3.zip or
        unidbg-fetch-qsign.3.zip.zip, and cannot find unidbg-fetch-qsign.3.zip.ZIP, period.

**Comment by wzq10314** [comment]
> 手动解压报错内容 Archive: unidbg-fetch-qsign.3.zip End-of-central-directory signature not found. Either this file is not a zipfile, or it constitutes one disk of a multi-part archive. In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive. unzip: cannot find zipfile directory in one of unidbg-fetch-qsign.3.zip or unidbg-fetch-qsign.3.zip.zip, and cannot find unidbg-fetch-qsign.3.zip.ZIP, period.

我看了眼压缩包才1kb，压缩包不完整导致的吧，emmmm下了几次都是1kb，是不是佬服务器那边有点问题

**Comment by CikeyQi** [comment]
很抱歉，由于官方unidbg-fetch-qsign项目被删库，脚本资源是从官方仓库下载的，使用导致无法下载资源，后续我们会尝试解决

**Comment by CikeyQi** [comment]
已修复，Have a Good Time.

**Comment by wzq10314** [comment]
> 已修复，Have a Good Time.

非常感谢，主要我自己搭的最近时间一长就出现错误代码，所以我打算试试你的脚本看看能不能解决这个问题
Oct 22 15:56:50 VM-4-2-debian bash[247469]: [FEKit_]info: qq_sign.h:156 [GetSign] cmd:Messa>
Oct 22 15:56:50 VM-4-2-debian bash[247469]: FEBound.transform(2621fbb11b751062a1c0e98b8b6ca>
Oct 22 15:56:50 VM-4-2-debian bash[247469]: [FEKit_]error: sign_tail_manager.h:147 tryReque>
Oct 22 15:56:50 VM-4-2-debian bash[247469]: [FEKit_]error: sign_tail_manager.h:161 curStatu>
Oct 22 15:56:51 VM-4-2-debian bash[247469]: [FEKit_]info: qq_sign.h:156 [GetSign] cmd:Messa>
Oct 22 15:56:51 VM-4-2-debian bash[247469]: FEBound.transform(440b776a3df68707bae1e4a416787>
Oct 22 15:56:51 VM-4-2-debian bash[247469]: [FEKit_]error: sign_tail_manager.h:147 tryReque>
Oct 22 15:56:51 VM-4-2-debian bash[247469]: [FEKit_]error: sign_tail_manager.h:161 curStatu>
Oct 22 15:56:53 VM-4-2-debian bash[247469]: [FEKit_]info: qq_sign.h:156 [GetSign] cmd:Messa>
Oct 22 15:56:53 VM-4-2-debian bash[247469]: FEBound.transform(44c1a59fd71b25709887b8a41678d>
Oct 22 15:56:53 VM-4-2-debian bash[247469]: [FEKit_]error: sign_tail_manager.h:147 tryReque>
Oct 22 15:56:53 VM-4-2-debian bash[247469]: [FEKit_]error: sign_tail_manager.h:161 curStatu>
Oct 22 15:56:54 VM-4-2-debian bash[247469]: [FEKit_]info: qq_sign.h:156 [GetSign] cmd:Messa>
Oct 22 15:56:54 VM-4-2-debian bash[247469]: FEBound.transform(331006f83e0001080001000100000>
Oct 22 15:56:54 VM-4-2-debian bash[247469]: [FEKit_]error: sign_tail_manager.h:147 tryReque>
Oct 22 15:56:54 VM-4-2-debian bash[247469]: [FEKit_]error: sign_tail_manager.h:161 curStatu>
Oct 22 15:56:56 VM-4-2-debian bash[247469]: [FEKit_]info: qq_sign.h:156 [GetSign] cmd:Messa>
Oct 22 15:56:56 VM-4-2-debian bash[247469]: FEBound.transform(350875e4d940b6e0aae4e6e434aaa>
Oct 22 15:56:56 VM-4-2-debian bash[247469]: [FEKit_]error: sign_tail_manager.h:147 tryReque>
Oct 22 15:56:56 VM-4-2-debian bash[247469]: [FEKit_]error: sign_tail_manager.h:161 curStatu>
Oct 22 15:56:57 VM-4-2-debian bash[247469]: [FEKit_]info: qq_sign.h:156 [GetSign] cmd:Messa>
Oct 22 15:56:57 VM-4-2-debian bash[247469]: FEBound.transform(08d18b08080db298416c1532bd26c>
Oct 22 15:56:57 VM-4-2-debian bash[247469]: [FEKit_]error: sign_tail_manager.h:147 tryReque>
Oct 22 15:56:57 VM-4-2-debian bash[247469]: [FEKit_]error: sign_tail_manager.h:161 curStatu>
Oct 22 16:27:33 VM-4-2-debian bash[247469]: [FEKit_]info: device_info.h:534 534
Oct 22 16:27:33 VM-4-2-debian bash[247469]: [FEKit_]info: device_info.h:536 536
Oct 22 16:27:33 VM-4-2-debian bash[247469]: [FEKit_]info: device_info.h:538 538
Oct 22 16:27:33 VM-4-2-debian bash[247469]: [FEKit_]info: device_token.h:276 begin pack
Oct 22 16:27:33 VM-4-2-debian bash[247469]: [FEKit_]info: device_token.h:278 pack buff resu>
Oct 22 16:27:33 VM-4-2-debian bash[247469]: [FEKit_]info: device_token.h:293 begin sendmess>
Oct 22 16:27:33 VM-4-2-debian bash[247469]: FEBound.transform(39f14ee5e2e3f542d47fbba528317>
Oct 22 16:27:33 VM-4-2-debian bash[247469]: [FEKit_]error: ChannelManager.cpp:81 o3cm@S: ge>
Oct 22 16:27:33 VM-4-2-debian bash[247469]: uin = 570502551, id = 34, sendPacket(cmd = trpc>
Oct 22 16:27:33 VM-4-2-debian bash[247469]: [FEKit_]info: qq_sign.h:156 [GetSign] cmd:trpc.>
Oct 22 16:27:33 VM-4-2-debian bash[247469]: FEBound.transform(34601d153640be84f6d8010800010>
Oct 22 16:27:33 VM-4-2-debian bash[247469]: [FEKit_]info: ChannelManager.cpp:121 origin cmd>
Oct 22 16:27:33 VM-4-2-debian bash[247469]: [FEKit_]error: ChannelManager.cpp:124 [ChannelM>
Oct 22 16:27:33 VM-4-2-debian bash[247469]: [FEKit_]info: device_token.h:316 response len :>
Oct 22 16:27:33 VM-4-2-debian bash[247469]: [FEKit_]info: device_token.h:339 DeviceToken::s>
lines 962-1000/1000 (END)
Oct 22 15:56:50 VM-4-2-debian bash[247469]: [FEKit_]info: qq_sign.h:156 [GetSign] cmd:MessageSvc.PbSendMsg
Oct 22 15:56:50 VM-4-2-debian bash[247469]: FEBound.transform(2621fbb11b751062a1c0e98b8b6ca722143b4350bce2010800010001000001000000000000cff445f0) => d8ebe452603abd9568ddcfc481>
Oct 22 15:56:50 VM-4-2-debian bash[247469]: [FEKit_]error: sign_tail_manager.h:147 tryRequestTail
Oct 22 15:56:50 VM-4-2-debian bash[247469]: [FEKit_]error: sign_tail_manager.h:161 curStatus is 2
Oct 22 15:56:51 VM-4-2-debian bash[247469]: [FEKit_]info: qq_sign.h:156 [GetSign] cmd:MessageSvc.PbSendMsg
Oct 22 15:56:51 VM-4-2-debian bash[247469]: FEBound.transform(440b776a3df68707bae1e4a41678776f6f13010800010001000001000064aa8f4000000000cff445f0) => 0ea6870785445baa0463c420ea>
Oct 22 15:56:51 VM-4-2-debian bash[247469]: [FEKit_]error: sign_tail_manager.h:147 tryRequestTail
Oct 22 15:56:51 VM-4-2-debian bash[247469]: [FEKit_]error: sign_tail_manager.h:161 curStatus is 2
Oct 22 15:56:53 VM-4-2-debian bash[247469]: [FEKit_]info: qq_sign.h:156 [GetSign] cmd:MessageSvc.PbSendMsg
