### ISSUE TITLE
下载错误，已关闭vpn，选择的（1)国内路线

### ISSUE THREAD

**Issue by AhBumm** [CikeyQi/unidbg-fetch-qsign-shell#6]
正在下载并检查所需软件包，请稍等...
已安装 pv 工具，跳过安装
已安装 unzip 工具，跳过安装
已安装 Java 环境，跳过安装
1) 国内线路
2) 国外线路(暂时无法使用)
请选择线路：1
正在下载 unidbg-fetch-qsign，请稍等...
pv: -s: integer argument expected
下载失败，请检查网络连接或稍后再试

**Comment by CikeyQi** [comment]
ghproxy似乎被墙了

**Comment by CikeyQi** [comment]
已修复
