### ISSUE TITLE
无法下载本体

### ISSUE THREAD

**Issue by DYMTHH** [CikeyQi/unidbg-fetch-qsign-shell#7]

**Comment by qimubaibai** [comment]
遇到了同样的问题, 可以有其他方式上传文件吗
<img width="928" alt="image" src="https://github.com/CikeyQi/unidbg-fetch-qsign-shell/assets/84445513/041f1d3f-9ddb-4351-b780-d06e694983cf">

**Comment by CikeyQi** [comment]
> 遇到了同样的问题, 可以有其他方式上传文件吗
> <img width="928" alt="image" src="https://github.com/CikeyQi/unidbg-fetch-qsign-shell/assets/84445513/041f1d3f-9ddb-4351-b780-d06e694983cf">
> 

手动安装pv
