### ISSUE TITLE
go-cqhttp刷新token未初始化？

### ISSUE THREAD

**Issue by mhy9989** [CikeyQi/unidbg-fetch-qsign-shell#8]
go-cqhttp刷新token报错：
![IMG_1372](https://github.com/CikeyQi/unidbg-fetch-qsign-shell/assets/77878600/3a18ff22-6e82-4858-a8af-8b743daa18fb)
![IMG_1373](https://github.com/CikeyQi/unidbg-fetch-qsign-shell/assets/77878600/25403f24-4dcb-495a-b1d2-92fe1febaff8)
请问这种怎么解决？是设置问题还是什么问题？

**Comment by CikeyQi** [comment]
使用curl命令檢查一下qsign服務是否正常啟動，因為給出的日誌較少，暫時無法定位問題，如果方便的話，希望能提供啟動到報錯這段完整日誌

**Comment by mhy9989** [comment]
下面是重启后的日志
![image](https://github.com/CikeyQi/unidbg-fetch-qsign-shell/assets/77878600/b7a613d4-3fb8-487a-981a-11d9d544011a)
下面是go-cqhttp报错后的qsin日志
![image](https://github.com/CikeyQi/unidbg-fetch-qsign-shell/assets/77878600/cf49c0f1-e183-46d9-8158-fa63466dfe0b)

**Comment by CikeyQi** [comment]
我想看一下gocq的日誌

**Comment by mhy9989** [comment]
![image](https://github.com/CikeyQi/unidbg-fetch-qsign-shell/assets/77878600/8657c061-a12b-4cee-9085-1dc94b7dfcff)
![image](https://github.com/CikeyQi/unidbg-fetch-qsign-shell/assets/77878600/79f1693f-d32a-4420-b968-97edf822230f)
![image](https://github.com/CikeyQi/unidbg-fetch-qsign-shell/assets/77878600/48367243-bcd8-4096-8161-10cbc99387aa)
您好，gocq那边并未抛出其它日志，仅仅是个warning

**Comment by CikeyQi** [comment]
賬號是否能正常登錄並使用，若能正常使用則不用管WARN

**Comment by mhy9989** [comment]
账号可以使用，但不确定这种情况后是否会发生token失效等错误导致封禁的情况。

**Comment by CikeyQi** [comment]
能獲取到token即可

**Comment by mhy9989** [comment]
好的，我再试试，看看使用情况。
