### ISSUE TITLE
huggingface 项目没了

### ISSUE THREAD

**Issue by SFSHTime** [CikeyQi/unidbg-fetch-qsign-shell#9]
是被官方删了吗？之前部署qsign项目的号也没了。能在github上发出huggingface的源文件吗？小白，不会写dockerfile。求教，谢谢大佬！

**Comment by CikeyQi** [comment]
目前无法在HuggingFace部署Qsign了，官方开始围追堵截，本地Docker部署可以查看 [issues11](https://github.com/CikeyQi/QQsign_docs/issues/11)，也可以查看新的云端部署项目 [Koyeb部署签名服务](Koyeb部署签名服务)

**Comment by SFSHTime** [comment]
> 目前无法在HuggingFace部署Qsign了，官方开始围追堵截，本地Docker部署可以查看 [issues11](https://github.com/CikeyQi/QQsign_docs/issues/11)，也可以查看新的云端部署项目 [Koyeb部署签名服务](Koyeb%E9%83%A8%E7%BD%B2%E7%AD%BE%E5%90%8D%E6%9C%8D%E5%8A%A1)

哇塞，秒回，谢谢大佬！请问dockerfile 怎么安装宝塔面板呢？不会写，每次到安装的时候，脚本都下载好了，但是还是没动静

**Comment by CikeyQi** [comment]
> > 目前无法在HuggingFace部署Qsign了，官方开始围追堵截，本地Docker部署可以查看 [issues11](https://github.com/CikeyQi/QQsign_docs/issues/11)，也可以查看新的云端部署项目 [Koyeb部署签名服务](Koyeb%E9%83%A8%E7%BD%B2%E7%AD%BE%E5%90%8D%E6%9C%8D%E5%8A%A1)
> 
> 哇塞，秒回，谢谢大佬！请问dockerfile 怎么安装宝塔面板呢？不会写，每次到安装的时候，脚本都下载好了，但是还是没动静

你是准备本地部署吗？

**Comment by SFSHTime** [comment]
> > > 目前无法在HuggingFace部署Qsign了，官方开始围追堵截，本地Docker部署可以查看 [issues11](https://github.com/CikeyQi/QQsign_docs/issues/11)，也可以查看新的云端部署项目 [Koyeb部署签名服务](Koyeb%E9%83%A8%E7%BD%B2%E7%AD%BE%E5%90%8D%E6%9C%8D%E5%8A%A1)
> > 
> > 
> > 哇塞，秒回，谢谢大佬！请问dockerfile 怎么安装宝塔面板呢？不会写，每次到安装的时候，脚本都下载好了，但是还是没动静
> 
> 你是准备本地部署吗？

我是想看看huggingface怎么安装宝塔，顺便可以搭建点东西

**Comment by CikeyQi** [comment]
> > > > 目前无法在HuggingFace部署Qsign了，官方开始围追堵截，本地Docker部署可以查看 [issues11](https://github.com/CikeyQi/QQsign_docs/issues/11)，也可以查看新的云端部署项目 [Koyeb部署签名服务](Koyeb%E9%83%A8%E7%BD%B2%E7%AD%BE%E5%90%8D%E6%9C%8D%E5%8A%A1)
> > > 
> > > 
> > > 哇塞，秒回，谢谢大佬！请问dockerfile 怎么安装宝塔面板呢？不会写，每次到安装的时候，脚本都下载好了，但是还是没动静
> > 
> > 
> > 你是准备本地部署吗？
> 
> 我是想看看huggingface怎么安装宝塔，顺便可以搭建点东西

宝塔面板的安装不需要Docker，参考[这里](https://www.bt.cn/new/download.html)即可安装，在宝塔中可以安装Docker插件进行Docker容器管理

**Comment by SFSHTime** [comment]
> > > > > 目前无法在HuggingFace部署Qsign了，官方开始围追堵截，本地Docker部署可以查看 [issues11](https://github.com/CikeyQi/QQsign_docs/issues/11)，也可以查看新的云端部署项目 [Koyeb部署签名服务](Koyeb%E9%83%A8%E7%BD%B2%E7%AD%BE%E5%90%8D%E6%9C%8D%E5%8A%A1)
> > > > 
> > > > 
> > > > 哇塞，秒回，谢谢大佬！请问dockerfile 怎么安装宝塔面板呢？不会写，每次到安装的时候，脚本都下载好了，但是还是没动静
> > > 
> > > 
> > > 你是准备本地部署吗？
> > 
> > 
> > 我是想看看huggingface怎么安装宝塔，顺便可以搭建点东西
> 
> 宝塔面板的安装不需要Docker，参考[这里](https://www.bt.cn/new/download.html)即可安装，在宝塔中可以安装Docker插件进行Docker容器管理

我说的是在huggingface上安装宝塔面板

**Comment by CikeyQi** [comment]
> > > > > > 目前无法在HuggingFace部署Qsign了，官方开始围追堵截，本地Docker部署可以查看 [issues11](https://github.com/CikeyQi/QQsign_docs/issues/11)，也可以查看新的云端部署项目 [Koyeb部署签名服务](Koyeb%E9%83%A8%E7%BD%B2%E7%AD%BE%E5%90%8D%E6%9C%8D%E5%8A%A1)
> > > > > 
> > > > > 
> > > > > 哇塞，秒回，谢谢大佬！请问dockerfile 怎么安装宝塔面板呢？不会写，每次到安装的时候，脚本都下载好了，但是还是没动静
> > > > 
> > > > 
> > > > 你是准备本地部署吗？
> > > 
> > > 
> > > 我是想看看huggingface怎么安装宝塔，顺便可以搭建点东西
> > 
> > 
> > 宝塔面板的安装不需要Docker，参考[这里](https://www.bt.cn/new/download.html)即可安装，在宝塔中可以安装Docker插件进行Docker容器管理
> 
> 我说的是在huggingface上安装宝塔面板

HuggingFace本身的用户是没有管理员权限的，相当于一个Docker容器，而且开放的端口只有一个，我没有进行尝试，可以自己试试

**Comment by SFSHTime** [comment]
> > > > > 目前无法在HuggingFace部署Qsign了，官方开始围追堵截，本地Docker部署可以查看 [issues11](https://github.com/CikeyQi/QQsign_docs/issues/11)，也可以查看新的云端部署项目 [Koyeb部署签名服务](Koyeb%E9%83%A8%E7%BD%B2%E7%AD%BE%E5%90%8D%E6%9C%8D%E5%8A%A1)
> > > > 
> > > > 
> > > > 哇塞，秒回，谢谢大佬！请问dockerfile 怎么安装宝塔面板呢？不会写，每次到安装的时候，脚本都下载好了，但是还是没动静
> > > 
> > > 
> > > 你是准备本地部署吗？
> > 
> > 
> > 我是想看看huggingface怎么安装宝塔，顺便可以搭建点东西
> 
> 宝塔面板的安装不需要Docker，参考[这里](https://www.bt.cn/new/download.html)即可安装，在宝塔中可以安装Docker插件进行Docker容器管理

因为huggingface上面的容器只有docker

**Comment by CikeyQi** [comment]
并且，HuggingFace是非交互式部署，估计很难实现

**Comment by SFSHTime** [comment]
> > > > > > > 目前无法在HuggingFace部署Qsign了，官方开始围追堵截，本地Docker部署可以查看 [issues11](https://github.com/CikeyQi/QQsign_docs/issues/11)，也可以查看新的云端部署项目 [Koyeb部署签名服务](Koyeb%E9%83%A8%E7%BD%B2%E7%AD%BE%E5%90%8D%E6%9C%8D%E5%8A%A1)
> > > > > > 
> > > > > > 
> > > > > > 哇塞，秒回，谢谢大佬！请问dockerfile 怎么安装宝塔面板呢？不会写，每次到安装的时候，脚本都下载好了，但是还是没动静
> > > > > 
> > > > > 
> > > > > 你是准备本地部署吗？
> > > > 
> > > > 
> > > > 我是想看看huggingface怎么安装宝塔，顺便可以搭建点东西
> > > 
> > > 
> > > 宝塔面板的安装不需要Docker，参考[这里](https://www.bt.cn/new/download.html)即可安装，在宝塔中可以安装Docker插件进行Docker容器管理
> > 
> > 
> > 我说的是在huggingface上安装宝塔面板
> 
> HuggingFace本身的用户是没有管理员权限的，相当于一个Docker容器，而且开放的端口只有一个，我没有进行尝试，可以自己试试

就是因为我不会写dockerfile才来问的😂

**Comment by SFSHTime** [comment]
> 并且，HuggingFace是非交互式部署，估计很难实现

我看到B站有人在huggingface上装了koish，那就应该可以装宝塔，有了宝塔也就可以在上面装云崽、因为云崽的控制台是要登录账号才能用锅巴面板，所以我就说用宝塔安装云崽试试看。况且有了宝塔还能做很多事

**Comment by CikeyQi** [comment]
# 使用btpanel/bt作为初始镜像
FROM btpanel/bt

# 设置工作目录
WORKDIR /root

# 暴露容器的端口
EXPOSE 8888 888

**Comment by SFSHTime** [comment]
> 并且，HuggingFace是非交互式部署，估计很难实现

文件在这里https://github.com/initialencounter/koimux_bot/blob/master/docker/Dockerfile-lite-debian

**Comment by CikeyQi** [comment]
> > 并且，HuggingFace是非交互式部署，估计很难实现
> 
> 文件在这里https://github.com/initialencounter/koimux_bot/blob/master/docker/Dockerfile-lite-debian

他也没用到宝塔啊

**Comment by SFSHTime** [comment]
> # 使用btpanel/bt作为初始镜像
> FROM btpanel/bt
> 
> # 设置工作目录
> WORKDIR /root
> 
> # 暴露容器的端口
> EXPOSE 8888 888

谢谢！大佬可以看看这个链接，既然他用huggingface实现koish，那么是不是可以实现云崽呢😁

**Comment by CikeyQi** [comment]
之前我也在HuggingFace装过云崽，不过意义不大，HuggingFace不会存储你的数据，每次重启就会清空所有数据，相当于重装

**Comment by SFSHTime** [comment]
> > > 并且，HuggingFace是非交互式部署，估计很难实现
> > 
> > 
> > 文件在这里https://github.com/initialencounter/koimux_bot/blob/master/docker/Dockerfile-lite-debian
> 
> 他也没用到宝塔啊

因为koish有个网页管理的插件，不用登录QQ就可以在上面管理了。但是云崽的锅巴插件要登录QQ的情况下才能进入管理。你有说huggingface是非交互式的，所以需要一个管理的也就是宝塔来安装云崽了

**Comment by SFSHTime** [comment]
> 之前我也在HuggingFace装过云崽，不过意义不大，HuggingFace不会存储你的数据，每次重启就会清空所有数据，相当于重装

OK，谢谢

**Comment by SFSHTime** [comment]
大佬方便加个QQ吗，谢谢

**Comment by CikeyQi** [comment]
可以自己实测下，这个空间：https://huggingface.co/spaces/LeafLeafLeaf/Yunzai/

**Comment by CikeyQi** [comment]
> 大佬方便加个QQ吗，谢谢

在我个人主页有

**Comment by SFSHTime** [comment]
> 可以自己实测下，这个空间：https://huggingface.co/spaces/LeafLeafLeaf/Yunzai/

OK

**Comment by SFSHTime** [comment]
> # 使用btpanel/bt作为初始镜像
> FROM btpanel/bt
> 
> # 设置工作目录
> WORKDIR /root
> 
> # 暴露容器的端口
> EXPOSE 8888 888

按照这个为什么报错呢
ERROR: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
